name: Deploy MkDocs

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: write 

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install MkDocs
        run: pip install mkdocs mkdocs-material mkdocs-minify-plugin

      - name: Configure git auth for gh-pages push
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/tomasmiele/data-redes-neurais.git

      - name: Build and Deploy
        run: |
          mkdocs build --clean
          mkdocs gh-deploy --force --remote-branch gh-pages
