name: Deploy MkDocs

on:
  push:
    branches: [ "main" ]   # muda se sua branch principal não for "main"
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install MkDocs + Plugins
        run: |
          pip install --upgrade pip
          pip install mkdocs mkdocs-material mkdocs-minify-plugin

      - name: Build site
        run: mkdocs build --clean   # gera a pasta "site"

      - name: Verify built site (debug)
        run: |
          echo "Conteúdo da pasta site/"
          ls -R site | head -n 40

      - uses: actions/configure-pages@v5

      - uses: actions/upload-pages-artifact@v3
        with:
          path: 'site'

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - id: deployment
        uses: actions/deploy-pages@v4
